[package]
name = "ipasn_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.1"
tokio = { version = "1.47.1", features = ["macros", "net", "rt-multi-thread"] }

[build-dependencies]
prost-build = "0.14.1"
